---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(lubridate)
library(ggplot2)
library(ggplot2)
library(hexbin)
library(TSstudio)

setwd("E:/prazia/univer/DataScience/Ekz/acea-water-prediction")
df <- read.csv("Water_Spring_Madonna_di_Canneto.csv")


df$п.їDate = strptime(df$п.їDate, "%d/%m/%Y")
df$Date <- ymd(df$п.їDate)
ggplot(data=df, aes(x=Date, y=df$Flow_Rate_Madonna_di_Canneto)) + geom_line()
ggplot(data=df, aes(x=Date, y=df$Rainfall_Settefrati)) + geom_line()
ggplot(data=df, aes(x=Date, y=df$Temperature_Settefrati)) + geom_line()
head(df)

```


```{r}

library(lubridate)
library(imputeTS)

df$Rainfall_Settefrati <- na.interpolation(df$Rainfall_Settefrati, option = "spline")
ggplot(data=df, aes(x=Date, y=df$Flow_Rate_Madonna_di_Canneto)) + geom_line()
ggplot(data=df, aes(x=Date, y=df$Rainfall_Settefrati)) + geom_line()
ggplot(data=df, aes(x=Date, y=df$Temperature_Settefrati)) + geom_line()


```


```{r}

df$Temperature_Settefrati <- na.interpolation(df$Temperature_Settefrati, option = "spline")
ggplot(data=df, aes(x=Date, y=df$Flow_Rate_Madonna_di_Canneto)) + geom_line()
ggplot(data=df, aes(x=Date, y=df$Rainfall_Settefrati)) + geom_line()
ggplot(data=df, aes(x=Date, y=df$Temperature_Settefrati)) + geom_line()


```


```{r}

df$Flow_Rate_Madonna_di_Canneto <- na.interpolation(df$Flow_Rate_Madonna_di_Canneto, option = "spline")
data <- df$Flow_Rate_Madonna_di_Canneto
ggplot(data=df, aes(x=Date, y=df$Flow_Rate_Madonna_di_Canneto)) + geom_line()
ggplot(data=df, aes(x=Date, y=df$Rainfall_Settefrati)) + geom_line()
ggplot(data=df, aes(x=Date, y=df$Temperature_Settefrati)) + geom_line()

```




```{r}

library(data.table)

df <- df[order(df$Date), ]
df['Time_Interval'] = df$Date - shift(df$Date, n=1, fill=NA, type="lag")


```


```{r}

days <- df$Time_Interval


for(i in days)
{
  
  if(isTRUE(i > 1) || is.null(i))
  {
    print(i)
  }
    
}

```



```{r}

x <- ts(data, start=c(2012, 1, 1), end=c(2020, 30, 6), frequency=365)

library(forecast)
m0<-auto.arima(x)
m0

```


```{r}

plot(x)

```



```{r}

library(latex2exp)
x%>%diff(12)%>%diff(1)%>%autoplot()+theme_bw()+ylab(TeX("$(1-B)(1-B^2)X_t$}$"))+xlab("")

```


```{r}

library(urca)
t1=x%>%diff(12)%>%diff(1)%>%ur.df(lags = 6,type="none")
summary(t1)

```



```{r}

library(urca)
t2=x%>%diff(12)%>%diff(1)%>%ur.kpss(type="mu")
summary(t2)

```

```{r}

x%>%diff(12)%>%diff(1)%>%acf()+theme_bw()

```

```{r}

x%>%diff(12)%>%diff(1)%>%pacf()+theme_bw()

```

```{r}

qQ=list()
for(i in 1:14) qQ[[i]]=c(i-1,0)
qQ[[15]]=c(0,1)
qQ[[16]]=c(1,1)
pP=qQ

dt_params=c()
for(i in 1:16){
  for(j in 1:16){
    temp=c(pP[[i]][1],1,qQ[[j]][1],pP[[i]][2],1,
           qQ[[j]][2],12)
    dt_params=rbind(temp,dt_params)
  }
}
colnames(dt_params)=c("p","d","q","P","D","Q","T")
rownames(dt_params)=1:256

```


```{r}

models=vector("list",256)
for(i in 1:256){
  try(models[[i]]<-Arima(x,order = dt_params[i,1:3],
                    seasonal = list(order=dt_params[i,4:6],period=12),
                    lambda = NULL))
}

#models_archive <- models

```
```{r}
models_archive <- models
```


```{r}

library(caschrono)
aa=rep(NA,256)
for(i in 1:256){
  if(length(models[[i]]$residuals)>1){
    a=Box.test.2(x = models[[i]]$residuals,nlag = 10,type = "Box-Pierce")
    z=prod(1-(a[,2]<.05))
    if(z==1) aa[i]="y"
    else aa[i]="n"
  }
 
}
dt_params2=data.frame(dt_params)
dt_params2$residuals=aa

```


```{r}

aic=rep(NA,256)
model_names=rep(NA,256)
for(i in 1:256){
  if(length(models[[i]]$aic)>0){
    aic[i]=models[[i]]$aic
    model_names[i]=as.character(models[[i]])
  }
}
dt_params2$aic=aic
dt_params2$model=model_names

```



```{r}

library(DT)
dt_params2$aic=round(dt_params2$aic,4)
dt_params2=na.omit(dt_params2)
datatable(dt_params2,rownames = F)

```


```{r}


i=as.numeric(rownames(dt_params2)[which(dt_params2$aic<20150)])
res=sapply(i, function(x)as.character(models[[x]]))
res
i


```



```{r}

x_test=sapply(i, function(x)t_stat(models[[x]]))
bb=rep(NA,23)
for(j in 1:23){
  temp=t(x_test[[j]])[,2]
  z=prod((temp<.05))
  bb[j]=z
}
bb

```

```{r}

min_aic = Inf
modelAIC = NaN
for (p3 in i)
{
    print(dt_params2[p3,]$aic)
    if(isTRUE(dt_params2[p3,]$aic < min_aic))
    {
        min_aic = dt_params2[p3,]$aic
        modelAIC = dt_params2[p3,]$model
    }
}

print(min_aic)
print(modelAIC)


```

```{r}

x_tr <- window(x,end=2019) 
fit <- Arima(x_tr,order = c(13,1,0),
                    seasonal = list(order=c(0,1,1),period=12),
                    lambda = NULL)
f_fit<-forecast(fit)

autoplot(x_tr, series="Data") + 
  autolayer(fit$fitted, series="SARIMA(3,1,1)(0,1,1)[12]") +
  autolayer(f_fit, series="Prediction") +
  xlab("Year") + ylab("Departures") + ggtitle("Permanent Departures") + theme_bw()+theme(legend.title = element_blank(),legend.position = "bottom")


```
















